# Fetch LangSmith Logs

## Fetch Raw Logs

In [6]:
from packages.dev_thesis.langsmith_utils import LangsmithUtils
import pandas as pd

In [2]:
langsmith = LangsmithUtils()
langsmith.get_lansmith_traces(project_name='non-technical-stakeholders',save_to='non-technical-stakeholders')

Langsmith client initialized successfully
Client (API URL: https://api.smith.langchain.com)
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': "it's performing well WoW"}
{'quantitative_score': 1.0, 'qualitative_score': "it's performing well WoW"}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 0.0, 'qualitative_score': ''}
{'quantitative_score': 0.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 0.0, 'qualitative_score': 'didnt produce any result'}
{'quantitative_score': 0.0, 'qualitative_score': 'didnt produce any result'}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 0.0, 'qualitative_score': ''}
{'quantitative_score': 0.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 0.0, 'qualitative_score': 'wrong result'}
{'quantitative_score': 0.0, 'qualitative_score': 'wrong result'}
{'quantitative_score': 0.0, 'qualitative_score': 'wrong results, it gave me a list of 1s and not the actual number of days'}
{'quantitative_score': 0.0, 'qualitative_score': 'wrong results, it gave me a list of 1s and not the actual number of days'}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 0.0, 'qualitative_score': 'model refused to answer'}
{'quantitative_score': 0.0, 'qualitative_score': 'model refused to answer'}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': 0.0, 'qualitative_score': 'error'}
{'quantitative_score': 0.0, 'qualitative_score': 'error'}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 0.0, 'qualitative_score': 'two separete questions'}
{'quantitative_score': 0.0, 'qualitative_score': 'two separete questions'}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': 0.0, 'qualitative_score': ''}
{'quantitative_score': 0.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 0.0, 'qualitative_score': 'didnt contain the data for some weeks'}
{'quantitative_score': 0.0, 'qualitative_score': 'didnt contain the data for some weeks'}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': 0.0, 'qualitative_score': 'Did not understand a follow-up question on an initial question'}
{'quantitative_score': 0.0, 'qualitative_score': 'Did not understand a follow-up question on an initial question'}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': 0.0, 'qualitative_score': "Didn't understand the context"}
{'quantitative_score': 0.0, 'qualitative_score': "Didn't understand the context"}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': 1.0, 'qualitative_score': 'Very useful for viewing long lists of products'}
{'quantitative_score': 1.0, 'qualitative_score': 'Very useful for viewing long lists of products'}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': 0.0, 'qualitative_score': "It doesn't respond to if the trend is going up or down and if it's a positive outcome"}
{'quantitative_score': 0.0, 'qualitative_score': "It doesn't respond to if the trend is going up or down and if it's a positive outcome"}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': 1.0, 'qualitative_score': 'Close, some data is missing but gave what I asked for with more'}
{'quantitative_score': 1.0, 'qualitative_score': 'Close, some data is missing but gave what I asked for with more'}
{'quantitative_score': 0.0, 'qualitative_score': "It didn't continue in the context of discussion that we were in :-) "}
{'quantitative_score': 0.0, 'qualitative_score': "It didn't continue in the context of discussion that we were in :-) "}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': 1.0, 'qualitative_score': 'Correct response and properly structured'}
{'quantitative_score': 1.0, 'qualitative_score': 'Correct response and properly structured'}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': None, 'qualitative_score': None}
{'quantitative_score': 1.0, 'qualitative_score': ''}
{'quantitative_score': 1.0, 'qualitative_score': ''}

,name,input,output,feedback_score,feedback_comment,error,latency,prompt_tokens,completion_tokens,total_tokens
6b117751-c4b5-413f-9823-e107b5d6de33,RunnableSequence,[{'input': 'For all products types sold last y...,```sql\nWITH last_year_dates AS (\n SELECT\n ...,NaN,None,None,10.978871,1579,328,1907
b8f0f904-0ce9-48d1-8139-d42f8f15107b,RunnableSequence,[{'input': 'For all products types sold last y...,"```sql\nSELECT \n product_type,\n SUM(gross_...",1.0,,None,3.200784,1627,80,1707
8e8e66af-1f19-4798-8514-e32ebd2c8c35,RunnableSequence,[{'input': 'give me the sales and units sold W...,```sql\nWITH weekly_sales AS (\n SELECT\n ...,1.0,it's performing well WoW,None,11.284254,1612,375,1987
4e27b11d-3ae6-428c-b93a-73b798d8465d,RunnableSequence,[{'input': 'what's the average bastket size by...,"```sql\nSELECT \n product_category,\n COUNT(...",1.0,,None,3.988676,1466,68,1534
74f00f94-e102-4a47-806e-d4f5bf5f4d2f,RunnableSequence,"[{'input': 'historically, which month had the ...",```sql\nSELECT \n EXTRACT(YEAR FROM purchase_...,1.0,,None,3.791342,1347,80,1427
...,...,...,...,...,...,...,...,...,...,...
34e10246-1c7a-4e55-90be-30b4b9cf9b42,RunnableSequence,[{'input': 'What were the sales for men's polo...,"```sql\nSELECT \n product_colour, \n SUM(gro...",NaN,None,None,6.683820,1265,92,1357
eb6d8404-4ce7-4959-bc83-972a70e552b9,RunnableSequence,[{'input': 'give me a list of child asins sold...,"```sql\nSELECT \n purchase_date,\n child_asi...",NaN,None,None,4.227819,1231,90,1321
b87003d5-aff5-411b-adde-5e692c28bf53,RunnableSequence,[{'input': 'give me the result by each of thes...,"```sql\nSELECT \n product_marketing_category,...",NaN,None,None,4.047587,1150,79,1229
65531314-1ab4-4200-a304-0163dbc5504d,RunnableSequence,[{'input': 'How many units were sold of Male U...,```sql\nSELECT \n SUM(units_sold) AS total_un...,NaN,None,None,4.325422,1107,64,1171
0d8bcfd6-e0e0-4f05-af88-2a122eb9a9a9,RunnableSequence,[{'input': 'What were the sales for men's polo...,"```sql\nSELECT \n product_colour,\n SUM(gros...",1.0,,None,4.384503,1265,91,1356

## Fetch Clean Logs

In [5]:
from packages.dev_thesis.langsmith_utils import LangsmithUtils
langsmith = LangsmithUtils()

df = langsmith.get_lansmith_clean_traces(from_path=r'G:\My Drive\Profissional & Acadêmico\Mestrados\DTU\5_thesis\dev_thesis\data\de_data\processed_results\langsmith\non-technical-stakeholders.xlsx', save_to='langsmith_results_clean_non-technical-stakeholders')
df.head()

Langsmith client initialized successfully
Client (API URL: https://api.smith.langchain.com)

,id,sql_query,user_question,correctness,error_classification
0,6b117751-c4b5-413f-9823-e107b5d6de33,```sql\nWITH last_year_dates AS (\n SELECT\n ...,[{'input': 'For all products types sold last y...,None,NaN
1,b8f0f904-0ce9-48d1-8139-d42f8f15107b,"```sql\nSELECT \n product_type,\n SUM(gross_...",[{'input': 'For all products types sold last y...,y,NaN
2,8e8e66af-1f19-4798-8514-e32ebd2c8c35,```sql\nWITH weekly_sales AS (\n SELECT\n ...,[{'input': 'give me the sales and units sold W...,y,it's performing well WoW
3,4e27b11d-3ae6-428c-b93a-73b798d8465d,"```sql\nSELECT \n product_category,\n COUNT(...","[{'input': ""what's the average bastket size by...",y,NaN
4,74f00f94-e102-4a47-806e-d4f5bf5f4d2f,```sql\nSELECT \n EXTRACT(YEAR FROM purchase_...,"[{'input': 'historically, which month had the ...",y,NaN

## Final Tranformation of the Output
1 -  Extract Input from user_question columns

In [10]:
# read excel file to df
df = pd.read_excel(r'G:\My Drive\Profissional & Acadêmico\Mestrados\DTU\5_thesis\dev_thesis\data\de_data\processed_results\langsmith\langsmith_results_clean_non-technical-stakeholders.xlsx')

In [14]:
import pandas as pd
import ast

# Assuming you have a dataframe 'df' with a column 'user_question'
def extract_input(s):
    try:
        # Use ast.literal_eval to safely evaluate the string as a Python literal
        data = ast.literal_eval(s)
        # Extract the 'input' from the first dictionary in the list
        return data[0]['input']
    except (ValueError, SyntaxError, KeyError, IndexError):
        # Return None or some error indicator if parsing fails
        return None

# Apply the function to create a new column
df['extracted_input'] = df['user_question'].apply(extract_input)

# Now 'extracted_input' column will contain the input string
print(df['extracted_input'])

df

0      For all products types sold last year which on...
1      For all products types sold last year, which o...
2      give me the sales and units sold WoW for each ...
3      what's the average bastket size by product cat...
4      historically, which month had the highest numb...
                             ...
121    What were the sales for men's polo shirt by pr...
122    give me a list of child asins sold in the last...
123         give me the result by each of these products
124    How many units were sold of Male Underwear and...
125    What were the sales for men's polo shirt by pr...
Name: extracted_input, Length: 126, dtype: object

,Unnamed: 0,id,sql_query,user_question,correctness,error_classification,extracted_input
0,0,6b117751-c4b5-413f-9823-e107b5d6de33,```sql\nWITH last_year_dates AS (\n SELECT\n ...,[{'input': 'For all products types sold last y...,NaN,NaN,For all products types sold last year which on...
1,1,b8f0f904-0ce9-48d1-8139-d42f8f15107b,"```sql\nSELECT \n product_type,\n SUM(gross_...",[{'input': 'For all products types sold last y...,y,NaN,"For all products types sold last year, which o..."
2,2,8e8e66af-1f19-4798-8514-e32ebd2c8c35,```sql\nWITH weekly_sales AS (\n SELECT\n ...,[{'input': 'give me the sales and units sold W...,y,it's performing well WoW,give me the sales and units sold WoW for each ...
3,3,4e27b11d-3ae6-428c-b93a-73b798d8465d,"```sql\nSELECT \n product_category,\n COUNT(...","[{'input': ""what's the average bastket size by...",y,NaN,what's the average bastket size by product cat...
4,4,74f00f94-e102-4a47-806e-d4f5bf5f4d2f,```sql\nSELECT \n EXTRACT(YEAR FROM purchase_...,"[{'input': 'historically, which month had the ...",y,NaN,"historically, which month had the highest numb..."
...,...,...,...,...,...,...,...
121,121,34e10246-1c7a-4e55-90be-30b4b9cf9b42,"```sql\nSELECT \n product_colour, \n SUM(gro...","[{'input': ""What were the sales for men's polo...",NaN,NaN,What were the sales for men's polo shirt by pr...
122,122,eb6d8404-4ce7-4959-bc83-972a70e552b9,"```sql\nSELECT \n purchase_date,\n child_asi...",[{'input': 'give me a list of child asins sold...,NaN,NaN,give me a list of child asins sold in the last...
123,123,b87003d5-aff5-411b-adde-5e692c28bf53,"```sql\nSELECT \n product_marketing_category,...",[{'input': 'give me the result by each of thes...,NaN,NaN,give me the result by each of these products
124,124,65531314-1ab4-4200-a304-0163dbc5504d,```sql\nSELECT \n SUM(units_sold) AS total_un...,[{'input': 'How many units were sold of Male U...,NaN,NaN,How many units were sold of Male Underwear and...
125,125,0d8bcfd6-e0e0-4f05-af88-2a122eb9a9a9,"```sql\nSELECT \n product_colour,\n SUM(gros...","[{'input': ""What were the sales for men's polo...",y,NaN,What were the sales for men's polo shirt by pr...

In [15]:
# save df to excel
df.to_excel(r'G:\My Drive\Profissional & Acadêmico\Mestrados\DTU\5_thesis\dev_thesis\data\de_data\processed_results\langsmith\non-technical-stakeholders_extracted_values.xlsx', index=False)

: